### ISSUE TITLE
Request for step interpolation in TSI window

### ISSUE THREAD

**Issue by SamWSP** [Azure-Samples/azure-digital-twins-unreal-integration#1]
Request to update the TSI app and connecting Unreal functionality.
Graphs to be able to display data in steps as well as curved mode.
Would be useful when displaying Boolean data, for example occupancy or lights in the sample project.

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [X] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

**Comment by marvin-garcia** [comment]
Feature has been added and merged to main branch.
