### ISSUE TITLE
ObjectNotFound, PathNotFound

### ISSUE THREAD

**Issue by RobMDoe** [Azure-Samples/azure-digital-twins-unreal-integration#4]
> Please provide us with the following information:
> ---------------------------------------------------------------
- [x] bug report 
>
Not getting past Step 1 from hyperlink, ‘follow these instructions’, ‘Clone repository in Could Shell’ to run the required deployment scripts. 
>
Copied git clone repo and pasted into Windows PowerShell with Azure CLI and NodeJS. 
ObjectNotFound (git:string). 
PathNotFound (C:\Users\rober> git clone https://github.com/Azure-Samples/azure-digital-twins-unreal-integration>> cd azure-digital-twins-unreal-integration).
>
Expected: object and path found.
> 
Windows 11
>
Pro 21H2
> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by asergaz** [comment]
Relates with: https://docs.microsoft.com/en-us/answers/questions/708178/index.html

**Comment by asergaz** [comment]
@stevebus @SamWSP @3DStephen can you please take a look? Thanks!

**Comment by RobMDoe** [comment]
I've progressed, using Windows PowerShell Cloud Shell. Thought Powershell alone would work. On to Step 2 but BPAdtLinkSetup not showing up in Utility folder. AdtLink Content/AdtLink all good, Show Plugin Content and Show Engine Content both checked. Will repeat workflow, keep working through etc.

**Comment by stevebus** [comment]
Hey @RobMDoe  - sorry for the delayed response.  Let us know if you continue to have trouble and we can pull in the right people to help.

**Comment by RobMDoe** [comment]
Hi Steve. Fine now until Step 3 'Simulate Devices'. Have used GIT in Windows CLI to clone 'mock-devices' and 'azure-digital-twins-unreal-integration' to my root folder C:\users\rober. Have copied hvac.ts, index.ts, smartbinary.ts files between as instructed. Changed path to src/client (incidentally, the copied code attaches client to npm), then > npm ci && npm run build. The app doesn't build. Instead, errors culminate with,
npm ERR! Build failed with error code: 1
npm ERR! A complete log of this run can be found in:
npm ERR! C:\Users\rober\AppData\Local\npm-cache\_logs\2022-02-04T23_36_02_363Z-debug.log

[2022-02-04T23_36_02_363Z-debug - Copy.log](https://github.com/Azure-Samples/azure-digital-twins-unreal-integration/files/8006921/2022-02-04T23_36_02_363Z-debug.-.Copy.log)
)
Any advice welcome. Thanks.

**Comment by AshokPeddakotla-MSFT** [comment]
@stevebus Could you please share your insights on the latest issue?
